// <auto-generated />
using System;
using LibraryAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace APIPractice.Migrations
{
    [DbContext(typeof(LibraryAPIContext))]
    [Migration("20200609204814_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("LibraryAPI.Models.Genre", b =>
                {
                    b.Property<int>("GenreId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("GenreDescription");

                    b.Property<string>("GenreName");

                    b.Property<int?>("StoryId");

                    b.HasKey("GenreId");

                    b.HasIndex("StoryId");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            GenreId = 1,
                            GenreDescription = "A Collection of Short Horror Stories",
                            GenreName = "Horror"
                        },
                        new
                        {
                            GenreId = 2,
                            GenreDescription = "A Collection of Short Comedic Stories",
                            GenreName = "Comedy"
                        },
                        new
                        {
                            GenreId = 3,
                            GenreDescription = "A Collection of Short Drama Stories",
                            GenreName = "Drama"
                        },
                        new
                        {
                            GenreId = 4,
                            GenreDescription = "A Collection of Short Adventure Stories",
                            GenreName = "Adventure"
                        },
                        new
                        {
                            GenreId = 5,
                            GenreDescription = "A Collection of Short Suspenseful Stories",
                            GenreName = "Suspenseful"
                        },
                        new
                        {
                            GenreId = 6,
                            GenreDescription = "A Collection of Short Poems",
                            GenreName = "Poems"
                        });
                });

            modelBuilder.Entity("LibraryAPI.Models.Story", b =>
                {
                    b.Property<int>("StoryId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("StoryDetails");

                    b.Property<string>("StoryName");

                    b.HasKey("StoryId");

                    b.ToTable("Stories");

                    b.HasData(
                        new
                        {
                            StoryId = 1,
                            StoryDetails = "Id love to have an adventureTo different worlds where my heart can flyTo different worlds where my heart desiresAnd will be remembered until I die.Id love to have an adventureAlong with my precious penAnd write down all the things Ive witnessedAnd read it all again.Id love to have an adventureThrough the darkest part of the forestAnd meet the greatest beastsAnd see who is the toughest.Id love to have an adventureThrough the deepest part of the seaWhere a place I can find peaceAs if there is no living creature but me.Id love to have an adventureWhere mysterious mountains hide secretsThen Ill climb to its toppest partBy ignoring the chirping crickets.Id love to have an adventureWhere I can be my fullest selfTogether with my loved onesAnd finish the books on the shelf.Id love to have an adventureWith my eyes that is sharper than knifeIll face my battles, brave and humbleUntil I get to the Everlasting Life",
                            StoryName = "Id Love To Have An Adventure"
                        },
                        new
                        {
                            StoryId = 2,
                            StoryDetails = "Like crunchy cornflakesGold leaves rustle underfootBeauty in decay.",
                            StoryName = "Octobers Gold by Paul Holmes"
                        },
                        new
                        {
                            StoryId = 3,
                            StoryDetails = "It was one a.m. and Guy Halverson sat in his dark living room. He hadn't moved for over an hour. The accident earlier that evening kept playing over and over in his mind. The light turned red, but he was in a hurry and accelerated. An orange blur came from his right, and in a split second there was a violent jolt, then the bicyclist rolled across his hood and fell out of sight on the pavement. Horns blared angrily and he panicked, stepping on the gas and screeching away from the chaos into the darkness, shaken and keeping an eye on his rearview mirror until he got home.Why did you run, you idiot? He'd never committed a crime before this and punished himself by imagining years in jail, his career gone, his family gone, his future gone.Why not just go to the police right now? You can afford a lawyer.Then someone tapped on the front door and his world suddenly crumbled away beneath him. They found me. There was nothing he could do but answer it. Running would only make matters worse. His body trembling, he got up, went to the door and opened it. A police officer stood under the porch light.Mr. Halverson?asked the grim officer.He let out a defeated sigh.Yes. Let me —I am terribly sorry, but I'm afraid I have some bad news. Your son's bike was struck by a hit and run driver this evening. He died at the scene. I'm very sorry for your loss.",
                            StoryName = "The Acciden by Minnboy"
                        });
                });

            modelBuilder.Entity("LibraryAPI.Models.StoryGenre", b =>
                {
                    b.Property<int>("StoryGenreId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("GenreId");

                    b.Property<int>("StoryId");

                    b.HasKey("StoryGenreId");

                    b.HasIndex("GenreId");

                    b.HasIndex("StoryId");

                    b.ToTable("StoryGenre");
                });

            modelBuilder.Entity("LibraryAPI.Models.Genre", b =>
                {
                    b.HasOne("LibraryAPI.Models.Story")
                        .WithMany("Genres")
                        .HasForeignKey("StoryId");
                });

            modelBuilder.Entity("LibraryAPI.Models.StoryGenre", b =>
                {
                    b.HasOne("LibraryAPI.Models.Genre", "Genre")
                        .WithMany("Stories")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LibraryAPI.Models.Story", "Story")
                        .WithMany()
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
